version: "2.9"
networks:
  app_network:
    name: bmmnetowrk
    driver: bridge

services:

  mssql:
    build:
      context: .
      dockerfile: mssql/Dockerfile
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - app_network
    ports:
      - "1433:1433"
    volumes:
      - ~/apps/mssql/data:/usr/src/app/
    entrypoint: ./usr/src/app/entrypoint.sh
    environment:
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong**Password!
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    depends_on:
      - mssql
    image: bmm-wms
    networks:
      - app_network
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/healthCheck" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:sqlserver://mssql:1433;Database=WMSDatabase;Trusted_Connection=True",
        "spring.datasource.username":"SA",
        "spring.datasource.password":"yourStrong**Password!"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  postman:
    container_name: postmanTests
    image: postman/newman:alpine
    networks:
      - app_network
    build:
      context: .
      dockerfile: mssql/Dockerfile
    depends_on:
      app:
        condition: service_healthy
    links:
      - app
    command:
      run BMM-WMS.json -k
      --environment=BMM-WMS.json
      -r htmlextra,cli,json
      --reporter-htmlextra-export="reports/BMM-WMSAPITests.html"
      --reporter-json-export="reports/BMM-WMSAPITests.json"
    volumes:
      - ~/apps/postman:/etc/newman

