version: "3.9"
networks:
  app_network:
    name: bmmnetowrk
    driver: bridge

services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - app_network
    ports:
      - "1433:1433"
    volumes:
      - ~/apps/mssql/data:/usr/src/app/
    entrypoint: ./usr/src/app/entrypoint.sh
    environment:
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong**Password!
  check-mssql-started:
    image: jwilder/dockerize:0.6.1
    networks:
      - app_network
    depends_on:
      - mssql
    command: 'dockerize -wait=tcp://mssql:1433 -timeout 30s'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - check-mssql-started
      - mssql
    image: bmm-wms
    networks:
      - app_network
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:sqlserver://mssql:1433;Database=WMSDatabase;Trusted_Connection=True",
        "spring.datasource.username":"SA",
        "spring.datasource.password":"yourStrong**Password!"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  check-app-started:
    image: jwilder/dockerize:0.6.1
    networks:
      - app_network
    depends_on:
      - check-mssql-started
    command: 'dockerize -wait=tcp://app:8080 -timeout 30s'

  postman:
    container_name: postmanTests
    image: postman/newman:alpine
    networks:
      - app_network
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
      - mssql
      - check-mssql-started
      - check-app-started
    environment:
      - WAIT_HOSTS=app:8080
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    command:
      ./wait.sh
      run BMM-WMS.json -k
      --environment=BMM-WMS.json
      -r htmlextra,cli,json
      --reporter-htmlextra-export="reports/BMM-WMSAPITests.html"
      --reporter-json-export="reports/BMM-WMSAPITests.json"
    volumes:
      - ~/apps/postman:/etc/newman

